version: '3.8'

services:
  payment_service:
    container_name: payment_service 
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3059:3069
    volumes:
      - .:/go/src/app
    depends_on:
      - payment_service_db
  payment_service_db:
    container_name: payment_service_db
    image: mongo:6-jammy
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    