version: '3.8'

services:
  payment_service:
    container_name: payment_service 
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3059:3069
    volumes:
      - .:/go/src/app
    depends_on:
      payment_service_db:
        condition: service_healthy
      payment_service_queue:
        condition: service_healthy
  payment_service_db:
    container_name: payment_service_db 
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5435:5432
    volumes:
      - ./db:/var/lib/postgresql/data
      # - ./schema:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 30s
      timeout: 30s
      retries: 10
  payment_service_queue:
    container_name: payment_service_queue
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./queue:/data 
    healthcheck:
      test: "redis-cli -a ${REDIS_PASSWORD} --raw incr ping"
      interval: 30s
      timeout: 30s
      retries: 10