version: '3.8'

services:
  payment_service:
    container_name: payment_service 
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3059:3069
    volumes:
      - .:/go/src/app
    depends_on:
      - payment_service_db
  payment_service_db:
    container_name: payment_service_db 
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5435:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  payment_service_queue:
    container_name: payment_service_queue
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./queue:/data 

networks:
  default:
    name: tessera_network
    external: true