version: '3.8'

services:
  client_service:
    container_name: client_service
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - client_service_db
  client_service_db:
    container_name: client_service_db
    image: mongo:6-jammy
    restart: unless-stopped
    ports:
      - '27018:27017'
    volumes:
      - ./db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}