version: '3.8'

services:
  ticket_service:
    container_name: ticket_service
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3069:3069
    volumes:
      - .:/go/src/app
  ticket_service_db:
    container_name: ticket_service_db 
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5434:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
    depends_on:
      - ticket_service_db

networks:
  default:
    name: tessera_network
    external: true